name: Pull Request

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.8

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.13.1

      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun
            node_modules
          key: ${{ runner.OS }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.OS }}-bun-

      - name: Install dependencies
        run: bun install

      - name: Run the tests and checks
        run: |
          bun run lint
          bun run prettier-check
